
import React from 'react';

export const styles: { [key: string]: React.CSSProperties } = {
  container: {
    display: 'flex',
    flexDirection: 'column',
    backgroundColor: '#fff',
  },
  header: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '1rem 2rem',
    backgroundColor: '#ffffff',
    boxShadow: '0 2px 4px rgba(0,0,0,0.1)',
    position: 'sticky',
    top: 0,
    zIndex: 1000,
  },
  logo: {
    fontSize: '1.8rem',
    color: '#007aff',
    margin: 0,
  },
  navLink: {
    margin: '0 1rem',
    textDecoration: 'none',
    color: '#555',
    fontWeight: 500,
    transition: 'color 0.3s',
  },
  main: {
    flex: '1',
  },
  hero: {
    textAlign: 'center',
    padding: '5rem 2rem',
    backgroundColor: '#f0f8ff',
    borderRadius: '12px',
    margin: '2rem',
  },
  heroTitle: {
    fontSize: '3rem',
    color: '#007aff',
    marginBottom: '1rem',
    fontWeight: 700,
  },
  heroSubtitle: {
    fontSize: '1.2rem',
    color: '#555',
    maxWidth: '600px',
    margin: '0 auto 2rem auto',
  },
  ctaButton: {
    padding: '0.8rem 2rem',
    fontSize: '1rem',
    color: '#fff',
    backgroundColor: '#007aff',
    border: 'none',
    borderRadius: '50px',
    cursor: 'pointer',
    fontWeight: 'bold',
    transition: 'background-color 0.3s, transform 0.2s',
  },
  coursesSection: {
    padding: '4rem 2rem',
    backgroundColor: '#f8f9fa',
  },
  algorithmsSection: {
    padding: '4rem 2rem',
    backgroundColor: '#ffffff',
  },
  aboutSection: {
    padding: '4rem 2rem',
    backgroundColor: '#f8f9fa',
  },
  aboutText: {
    maxWidth: '800px',
    margin: '0 auto',
    textAlign: 'center',
    fontSize: '1.1rem',
    lineHeight: '1.8',
    color: '#555',
  },
  contactSection: {
    padding: '4rem 2rem',
    backgroundColor: '#ffffff',
    textAlign: 'center',
  },
  contactText: {
    fontSize: '1.1rem',
    color: '#555',
    marginBottom: '1.5rem',
  },
  contactInfo: {
    lineHeight: '1.8',
  },
  contactLink: {
    color: '#007aff',
    textDecoration: 'none',
    fontWeight: 500,
  },
  sectionTitle: {
    textAlign: 'center',
    fontSize: '2.5rem',
    marginBottom: '3rem',
    color: '#333',
  },
  coursesGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(340px, 1fr))',
    gap: '2rem',
    maxWidth: '1200px',
    margin: '0 auto',
  },
  courseCard: { // Icon card
    backgroundColor: '#ffffff',
    padding: '2rem',
    borderRadius: '12px',
    boxShadow: '0 4px 12px rgba(0,0,0,0.08)',
    textAlign: 'center',
    transition: 'transform 0.3s, box-shadow 0.3s',
    display: 'flex',
    flexDirection: 'column',
  },
  videoCourseCard: { // Video card
    backgroundColor: '#ffffff',
    borderRadius: '12px',
    boxShadow: '0 4px 12px rgba(0,0,0,0.08)',
    overflow: 'hidden',
    display: 'flex',
    flexDirection: 'column',
  },
  cardContent: {
      padding: '0 1.5rem 1.5rem 1.5rem',
      display: 'flex',
      flexDirection: 'column',
      flexGrow: 1,
  },
  videoContainer: {
    position: 'relative',
    paddingBottom: '56.25%', // 16:9 Aspect Ratio
    height: 0,
    overflow: 'hidden',
    flexShrink: 0,
  },
  videoIframe: {
    position: 'absolute',
    top: 0,
    left: 0,
    width: '100%',
    height: '100%',
    border: 'none',
  },
  videoCourseTitle: {
    fontSize: '1.4rem',
    marginTop: '1rem',
    marginBottom: '0.5rem',
    color: '#007aff',
  },
  videoCourseAuthor: {
    fontSize: '0.9rem',
    color: '#888',
    margin: '0 0 1rem 0',
  },
  courseIcon: {
    fontSize: '3rem',
    marginBottom: '1rem',
  },
  courseTitle: {
    fontSize: '1.5rem',
    marginBottom: '0.5rem',
    color: '#007aff',
  },
  iconCardDescription: {
    color: '#666',
    lineHeight: '1.6',
    flexGrow: 1,
  },
  videoCardDescription: {
      color: '#666',
      lineHeight: '1.6',
      flexGrow: 1,
  },
  footer: {
    textAlign: 'center',
    padding: '2rem',
    backgroundColor: '#f8f9fa',
    color: '#777',
    borderTop: '1px solid #e9ecef',
  },
  modalOverlay: {
    position: 'fixed',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.6)',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 2000,
    opacity: 1,
    transition: 'opacity 0.3s ease-in-out',
  },
  modalContent: {
    backgroundColor: '#fff',
    padding: '2rem 2.5rem',
    borderRadius: '12px',
    width: '90%',
    maxWidth: '600px',
    position: 'relative',
    boxShadow: '0 5px 15px rgba(0,0,0,0.3)',
    maxHeight: '80vh',
    overflowY: 'auto',
  },
  modalTitle: {
     fontSize: '2rem',
     color: '#007aff',
     margin: 0,
  },
  closeButton: {
    position: 'absolute',
    top: '1rem',
    right: '1.5rem',
    background: 'none',
    border: 'none',
    fontSize: '2rem',
    cursor: 'pointer',
    color: '#888',
  },
  codeBlock: {
    backgroundColor: '#f4f4f4',
    padding: '1rem',
    borderRadius: '8px',
    borderTopLeftRadius: '0',
    overflowX: 'auto',
    textAlign: 'left',
    fontSize: '0.9rem',
    margin: '0 0 1rem 0',
    border: '1px solid #ddd'
  }
};
